sudo: required
services:
  - docker
before_install:
  - docker build -t ajmaradiaga/studious-memory -f Dockerfile.dev .

script:
  - docker run -e CI=true ajmaradiaga/studious-memory npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  name: "studious-memory"
  env: "StudiousMemory-Env"
  bucket_name: "elasticbeanstalk-eu-west-1-899085916962"
  bucket_path: "studious-memory"
  on:
    branch: "master"


language: generic

