sudo: required
services:
  - docker
before_install:
  - docker build -t ajmaradiaga/studious-memory -f Dockerfile.dev .

script:
  - docker run -e CI=true ajmaradiaga/studious-memory npm run test -- --coverage

language: generic

